/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paquete;

import java.sql.*;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;

public class Inventario extends javax.swing.JPanel {

    DefaultTableModel mode;
    
    //1
    
            
            
            //2
    public Inventario() {
        initComponents();
        
        
        
        
        
        try {

            Class.forName("com.mysql.jdbc.Driver");
            Connection conexion = DriverManager.getConnection("jdbc:mysql://localhost/mercancia", "root", "");
            Statement stm = conexion.createStatement();
            ResultSet res = stm.executeQuery("SELECT * FROM mercancia");
            ResultSetMetaData rsMd = res.getMetaData();
            int numeroColumnas = rsMd.getColumnCount();

            DefaultTableModel modelo = new DefaultTableModel();
            this.tabla.setModel(modelo);
            tabla.setEnabled(false);
            for (int x = 1; x <= numeroColumnas; x++) {
                modelo.addColumn(rsMd.getColumnLabel(x));

            }

            while (res.next()) {
                Object[] fila = new Object[numeroColumnas];

                for (int y = 0; y < numeroColumnas; y++) {
                    fila[y] = res.getObject(y + 1);

                }

                modelo.addRow(fila);

            }

        } catch (ClassNotFoundException in) {
            in.printStackTrace();

        } catch (SQLException se) {
            se.printStackTrace();

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        txtTotal = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        labelSIgno = new javax.swing.JLabel();
        labelTotal = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btReal = new javax.swing.JButton();
        label2 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();

        setPreferredSize(new java.awt.Dimension(770, 335));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Producto", "Plantel", "Talla", "Cantidad", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Short.class, java.lang.Short.class, java.lang.Short.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.setAutoscrolls(false);
        tabla.setColumnSelectionAllowed(true);
        tabla.setName(""); // NOI18N
        tabla.setShowVerticalLines(false);
        jScrollPane1.setViewportView(tabla);
        tabla.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tabla.getColumnModel().getColumnCount() > 0) {
            tabla.getColumnModel().getColumn(1).setResizable(false);
            tabla.getColumnModel().getColumn(3).setResizable(false);
            tabla.getColumnModel().getColumn(4).setResizable(false);
            tabla.getColumnModel().getColumn(4).setHeaderValue("Precio");
        }

        jScrollPane2.setViewportView(jScrollPane1);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 360));

        txtTotal.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        txtTotal.setText("TOTAL");
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });
        add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 140, 90, 60));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, 120, 10));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, 120, 10));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 250, 120, 10));

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 30, 10, 80));

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 230, 10, 80));

        labelSIgno.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 20)); // NOI18N
        labelSIgno.setForeground(new java.awt.Color(51, 153, 0));
        labelSIgno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSIgno.setText("$");
        add(labelSIgno, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 60, -1, -1));

        labelTotal.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        labelTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                labelTotalKeyTyped(evt);
            }
        });
        add(labelTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, 100, 60));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("REAL");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 220, -1, -1));

        btReal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btReal.setText("INV REAL");
        btReal.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btRealStateChanged(evt);
            }
        });
        btReal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRealActionPerformed(evt);
            }
        });
        add(btReal, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 320, -1, -1));
        add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 260, 90, 40));
        add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 110, 120, 10));
        add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 300, 120, 10));

        jSeparator9.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, 10, 80));

        jSeparator10.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 230, 10, 80));
    }// </editor-fold>//GEN-END:initComponents

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        
        
        labelTotal.setText("0");
        int t = tabla.getRowCount();
        int c = 0;

        do {
            try {
                int f = c++;
                int n1 = Integer.parseInt(tabla.getValueAt(f, 4).toString());
                int n2 = Integer.parseInt(labelTotal.getText());
                int re = n1 + n2;
                labelTotal.setText(String.valueOf(re));
            } catch (Exception e) {

            }
        } while (c < t);       
    }//GEN-LAST:event_txtTotalActionPerformed

    private void labelTotalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_labelTotalKeyTyped
        
        
    }//GEN-LAST:event_labelTotalKeyTyped

    private void btRealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRealActionPerformed
       
       Ventas vt = new Ventas();
              
       System.out.print(vt.e);
       label2.setText(String.valueOf(vt.e)); 
        
        
    }//GEN-LAST:event_btRealActionPerformed

    private void btRealStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btRealStateChanged
       
       
        
        
        
    }//GEN-LAST:event_btRealStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btReal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel labelSIgno;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JTable tabla;
    private javax.swing.JButton txtTotal;
    // End of variables declaration//GEN-END:variables

    void setModel(DefaultTableModel mode) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

}
